/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module 'sst' {
  export interface Resource {
    WebApp: {
      type: 'sst.cloudflare.StaticSite';
      url: string;
    };
    Webdocs: {
      type: 'sst.cloudflare.Astro';
      url: string;
    };
  }
}
/// <reference path="sst-env.d.ts" />

import 'sst';
export {};
