# @name formLogin
# @description URL-encoded form submission (login)
# Content-Type is automatically set to application/x-www-form-urlencoded

POST https://httpbin.org/post

username = {{user}}
password = {{pass}}
remember = true
